config/routes.rb
 Rails.application.routes.draw do
  root to: 'welcomes#index'
  
  
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :services
  resources :details
  resources :carts
  resources :cart_items
  get '/search' => 'welcomes#search', :as => 'search_page'
  get '/details' => 'details#index', :as => 'details_page'
  devise_for :users
  resources :authors
   get '/authors/:id', action: :delete, controller: 'authors'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :books
   # get 'books' => 'books#index'
   # get 'book/new' => 'books#new' #controlleraction
   # post 'book/new' => 'books#create'
 end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
       if user.has_role :admin?
         can :manage, :all
       else
         can :read, :all
       end
    
   end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
# after_validation :set_status
  #  before_save :check_name_has_value
  # scope :check_name_length, ->{ where("LENGTH(name) > 5 ") }
  #  before_update :before_update_callback
  #  after_update :after_update_callback
  #  after_save :after_save_callback
  
  # private

  # def remove_whitespaces
  #    name.strip!
  #  end

  #  def set_status
  #    self.status = errors.empty?
  #  end

  # def check_name_has_value
  #   binding.pry
  #   if name.empty?
  #     a = Author.create(name: 'demo')
  #     a.save
  #   end
  # end

   # def before_update_callback
   #   Author.create(:name => 'before_update')
   # end

   # def after_update_callback
   #   Author.create(:name => 'after_update')
   # end

   # def after_save_callback
   #   Book.create(:name => 'i am after_save',:author_id => 1, :description => 'i am after_save book')
   # end

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author

	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items

#add to cart

def total_price
   self.items.pluck(:price).inject(:+)
end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :service
end

app/models/detail.rb
class Detail < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :service
	
	validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
resourcify
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :cart_items
	has_many :details
	resourcify
end

app/models/user.rb
class User < ApplicationRecord
 # before_action :configure_permitted_parameters, if: :devise_controller?

	#rolify :before_add => :before_add_method
	after_create :assign_default_role

 rolify
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end


  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
    @books = Book.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to details_path
    else
      render :new
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
    
  end
def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to authors_path
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to root_path
  end

  private

    def author_params
      params.require(:author).permit(:author_name, :author_description)
    end
 end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
	  @books = Book.all 
	end
	def new
	  @book = Book.new
	end
	def show 
	 @book = Book.find(params[:id])
	end 
	def edit
		@book = Book.find(params[:id])
	 end
	def destroy
		@book = Book.find(params[:id])
		if @book.destroy
			redirect_to root_path
		else
			flash[:alert] = 'error while deleting'
		end
	end
	def create 
		@book = Book.new(book_params)
		if @book.save
			redirect_to details_path
		else
			render new
		end
	end
	def update
		 @book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to books_path
		else 
			render :edit
		end 
	end
	def book_params
		params.require(:book).permit(:author_id, :author_name, :id, :book_name, :book_descriptions, :book_price, :image)
	end
	end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:create]	
	def index
		@cart = current_user.cart
		@users = User.all
		@cart_items = @cart.cart_items
	end
	def create 
		if current_user.present?
			@cart = current_cart(current_user)
			if @cart.cart_items.find_by_service_id(params[:welcome_page_id]).blank?
				@cart_items = @cart.cart_items.new(service_id: params[:welcome_page_id])
				if @cart_items.save
					@msg = "Item Added"
				end
			else
				@msg = "Alredy present"
			end
			respond_to do |format|
				format.js{}
			end
		else
			redirect_to :user_sign_in_path, flash[:notice] = "Login First"
		end
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
 before_action :authenticate_user!
 before_action :configure_permitted_parameters, if: :devise_controller?


  def index
    @user = User.all
    @services = Service.all
  end

 def new 
 end


 def user
 @user = User.find(params[:id]) 
 end

  def search
    # @services = Service.all
    if params[:search].blank?  
     redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
     @results = Service.all.where("lower(title) LIKE :search", search: @parameter)  
    end  
  end
end


959450 

app/helpers/application_helper.rb
module ApplicationHelper
	def has_role?(role)
		current_user && current_user.has_role?(role)
	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/index.html.erb
<center><h1>Welcome To Bookswagon <%= current_user.name %></h1></center> 
<center>
<div class="btn-group">
      <span > 
      <select  role="menu">
       <option value="1"><%= link_to "select your city", root_path%></option>
       <option value="2"><%= link_to "Delhi", root_path %></option>
       <option value="3"><%= link_to "Pune", root_path %></option>
       <option value="4"><%= link_to "Mumbai", root_path %></option>
        <option value="5"><%= link_to "Banglore", root_path %></option>
      </select></span> 
      
</div>
</center> 
<!--- optional dropdown list -->


<h1>
  
</h1>

<!-- search bar -->
<%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "search", :class => 'btn btn-dark',:name => nil%>  
    </div>  
  </div>  
<% end %><br>


<%- if has_role?(:admin) %>
<button type="button" class="btn btn-dark">
    <%= link_to 'Add More Services', new_service_path %>
</button><br>
<% end %>

<%#- if has_role?(:admin) %>
<!-- <button type="button" class="btn btn-dark">
    <%#= link_to 'Add Details', details_path %>
</button><br> -->
<%# end %>
<br>
<%#- if has_role?(:admin) %>
<button type="button" class="btn btn-dark">
    <%= link_to 'Authors List', details_path %>
</button>
<!-- <button type="button" class="btn btn-dark">
    <%#= link_to 'Book', books_path %>
</button> -->
<div class="row">
<%# end %>
<% @services.each do |services| %>
<div class="card" style="width: 15rem;"><br>
 <!--  <img src="..." class="card-img-top" alt="..."> -->
   <center><h5 class="card-title"><%= services.title %></h5></center> 
   <a href = "<%= detail_url(services) %> "
    <%= link_to image_tag(services.image.url, class: 'media-object'), services.image.url,  class: "col", width: "20%"%>
     </a> 
    
   <br>
    <div class="card-body">
      <!--<p class="card-text"><%= services.detail %></p>
      <h5 class="card-title"><%= services.price %></h5>
     <a href="#" class="btn btn-primary">Add Cart</a> -->
      <button type="button" class="btn btn-dark">
        <div>
        <%= link_to "Add", 'javascript:;', id: "simran_#{services.id}", class: "home-service-id" %>
        <%= link_to "Cart", carts_path %>
      </div>
      </button>
      
    </div>
  </div>
<% end %>
</div>



<script>
  $(document).ready(function(){
    $(".home-service-id").on('click', function(){     
      var welcome_page_id = $(this).attr('id')
      var welcome_page_id = welcome_page_id.split('simran_')[1]
      $.ajax({
        url: "<%= carts_path %>",
        type: "POST",
        data: {
          welcome_page_id: welcome_page_id
        }
      });
    });
  });
</script>

<br>
<center>
<p> Logout Your Account</p>
  <div class="column">
    <button type="button" class="btn btn-dark">
      <%= link_to 'logout', destroy_user_session_path, method: :delete%>
    </button>
  </div>

</center>

app/views/welcomes/search.html.erb
<button type="button" class="btn btn-dark">

<%= link_to "Back To Home Page", root_path %>
</button>

<h3>Search Result</h3> 
<div class="row">
 <% @results.each do |result| %>  
<div class="card" style="width: 18rem;">
    <div class="card-body">
    <%= image_tag result.image.url, class: "column", width: "20%" %>
    <h5 class="card-title"><%= result.title %></h5><br>
    <p class="card-detail"><%= result.detail %></p><br>
    <h4 class="card-price"><%= result.price %></h4><br>
</div>
</div>
<% end %>
</div>



    
   