config/routes.rb
 Rails.application.routes.draw do
  root to: 'welcomes#index'
  
  
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :services
  resources :details
  resources :carts
  resources :cart_items
  get '/search' => 'welcomes#search', :as => 'search_page'
  get '/details' => 'details#index', :as => 'details_page'
  devise_for :users
  resources :authors
   get '/authors/:id', action: :delete, controller: 'authors'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :books
   # get 'books' => 'books#index'
   # get 'book/new' => 'books#new' #controlleraction
   # post 'book/new' => 'books#create'
 end

app/models/detail.rb
class Detail < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :service
	
	validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
resourcify
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # before_action :set_offer, only: [:show]
   def index
    @details = Detail.all
    @authors = Author.all
    @service = Service.all
    @book = Book.all
      end
  def show
    @service = Service.find(params[:id])
     @book = Book.all
     end
  #      def set_offer
  #   @offer = {}
  #   @offer[:Cleaning] = {off: ['discount', '40%'], ext: ['https://www.youtube.com/watch?v=ykUNOlD3fDQ','https://www.youtube.com/watch?v=d01TEb7Gc8Y','https://www.youtube.com/watch?v=GrF_yZKzYm4','https://www.youtube.com/watch?v=qkkqfJ916fs']}
  #   @offer[:Acservices] = {off: ['discount', '30%'], ext: ['https://www.youtube.com/watch?v=s6NHxfKUkUo','https://www.youtube.com/watch?v=uzCmysQsE7U']}
  #   @offer[:Learning] = {off: ['discount', '20%'], ext: ['https://www.youtube.com/watch?v=flU7chIYKFc&t=1s','https://www.youtube.com/watch?v=9KaRDDFm8Iw&list=PLVxBmyedTVhTRQRYeZJfVBpz_12zwHc6Z','https://www.youtube.com/watch?v=rjx0EwdwP_M','']}
  #   @offer[:Yogafitness] = {off: ['discount', '10%'], ext: ['https://www.youtube.com/watch?v=BQFHmIf2dHg','https://www.youtube.com/watch?v=VaoV1PrYft4','https://www.youtube.com/watch?v=EDbjpMq9eBg']}
  #   @offer[:Painters] = {off: ['discount', '10%'], ext: ['https://www.youtube.com/watch?v=CRXCB_3gLok','https://www.youtube.com/watch?v=8xhi85pykFo']}
  #   @offer[:Salonathome] = {off: ['discount', '10%'], ext: ['https://www.youtube.com/watch?v=tZMMbbOTjmA ','https://www.youtube.com/watch?v=7dYKFEooTAE']}
  # end
   
  def new
    @detail = Detail.new
  end

 def create
  @detail = Detail.new(detail_params)
  if @detail.save
   flash[:notice] = "Successfully added new photo!"
   redirect_to root_path
  else
   flash[:alert] = "Error adding new photo!"
   render :new
  end
 end

 private

 #Permitted parameters when creating a photo. This is used for security reasons.
 def detail_params
  params.require(:detail).permit(:title, :description, :cost, :image)
 end

end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/index.html.erb
<button type="button" class="btn btn-dark"> 
  <%= link_to "Back To Home Page", root_path %>   
</button>

<%- if has_role?(:admin) %>
<button type="button" class="btn btn-dark">
    <%= link_to 'Add Details',new_detail_path %>
</button><br>
<% end %>
<br>
<%#- if has_role?(:admin) %>
<!-- <button type="button" class="btn btn-dark">
    <%#= link_to 'Authors', details_path %>
</button> -->

<!-- <button type="button" class="btn btn-dark">
	<%#= link_to "Activity", new_detail_path %>
</button>  -->  
<br><br>
<!-- <button type="button" class="btn btn-dark">
	<%#= link_to "next", details_page_path %>
</button> -->
<%- if has_role?(:admin) %>
<button type="button" class="btn btn-dark">
<%= link_to "New Author", new_author_path %>
</button>
<% end %>
<%- if has_role?(:admin) %> 
<button type="button" class="btn btn-dark">
    <%= link_to 'New Book', new_book_path %>
</button>
<% end %>
<h1>Authors</h1>

<table id="customers">
    <tr>
      <th>Author Name</th>
      <th>Author Description</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
    <% @authors.each do |a| %>
   <!--  <%# binding.pry %> -->
    <tr>
      <td><%= a.author_name %></td>
      <td><%= a.author_description %></td>
      <%- if has_role?(:admin) %> 
      <td><%= link_to "show", author_path(a) %></td>
      <td><%= link_to "Edit", edit_author_path(a) %></td>
      <td><%= link_to "Delete", author_path(a), method: :destroy ,data: { confirm: "Are you sure?" } %>
        <% end %>
      <!-- <td><%#= link_to "Destroy", author_path(a),method: :delete,data: { confirm: "Are you sure?" } %></td> -->
    <% end %>
    </table>


    

app/views/details/new.html.erb
<button type="button" class="btn btn-dark"> 
  <%= link_to "Back To Home Page", root_path %>   
</button>

<div class="page-header">
  <center>upload details</center>
</div>

<%= form_for @detail, html: { multipart: true } do |f| %><br>
  <% if @detail.errors.any? %>
    <div id="error_explanation"><br>
      <h2>
        <%= "#{pluralize(@detail.errors.count, "error")} prohibited this photo from being saved:" %><br>
      </h2>
      <ul>
        <% @detail.errors.full_messages.each do |msg| %>
          <li><br>
            <%= msg %>
          </li>
          <% end %><br>
      </ul><br>
    </div>
  <% end %>
<br>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <br>
  <!-- <div class="form-group">
    <%#= f.label :cost %>
    <%#= f.number_field :cost, class: 'form-control' %>
  </div>
<br> -->
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
<br>
  <div class="form-group">
    <button type="button" class="btn btn-dark">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
      </button>
    </div>
    
    <%= link_to "Cancel", root_path %>
<% end %>

app/views/details/show.html.erb
<button type="button" class="btn btn-dark"> 
  <%= link_to "Back To Home Page", root_path %>   
</button>

<!DOCTYPE html>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- <html>
<body>
  <div class="w3-container">
  <div class="w3-bar w3-black"> -->
    <%#@offer.each do |k, v| %>
     <!--  <button class="w3-bar-item w3-button tablink w3-red" onclick="openCity(event, <%#= k.to_s %>)"><%#= k.capitalize %></button>
    <%#end %> -->
  <!-- </div>
  <%# @offer.each do |k, v| %>
    <div id="<%#= k %>" class="w3-container w3-border city" style="display: <%#=  k == :cleaning ? 'block' : 'none' %>" >
      <h2><%#= k.capitalize %></h2>
      <p> Today offer </br>
        <%# v[:off].each do |s| %>
          <%#= s %>  
        </br>
        <%# end %>  
      </p>
      <h1> Recommended videos</h1></br>
        <% # v[:ext].each do |n| %>
          <%#= n %>  
          </br>
        <%# end %>  
     
    </div>
  <% #end %>
</div>
<script>
function openCity(evt, cityName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
  }
  document.getElementById(cityName.id).style.display = "block";
  evt.currentTarget.className += " w3-red";
}
</script>

  </body>
</html> -->
<center><%= image_tag @service.image.url, class: "column", width: "20%" %></center>
<h2><%= @service.title %></h2>
  <p1><%= @service.detail %></p1>
  <br><div class="column">
  <h4>Cost :- <%=  @service.price %></h4>
    <!--button type="button", class="btn1"></button-->
    <!--<button type="button", class="btn1"></button> -->
    <!--<div class="col img"> <%#=  image_tag(@service.image.url)%></div> -->
    <!--<div class="col img"> <%#=  image_tag(@service.image.url)%></div> -->
<br>
<center>
<h1> More books in the list </h1>
</center>

    <table id="customers">
    <tr>
      <th>Book Name</th>
      <th>Book Description</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
    <% @book.each do |b| %>
    <tr> 
    <td><%= b.book_name %></td>
    <td><%= b.book_descriptions %></td>
    <%- if has_role?(:admin) %>
      <td><%= link_to "show", book_path(b) %></td>
      <td><%= link_to "Edit", edit_book_path(b) %></td>
      <td><%= link_to "Delete", book_path(b), method: :destroy ,data: { confirm: "Are you sure?" } %></td>
<% end %>
<% end %>
    </table>


<center>
<p> Logout Your Account</p>
  <div class="column">
    <button type="button" class="btn btn-dark">
      <%= link_to 'logout', destroy_user_session_path, method: :delete%>
    </button>
  </div>

</center>